### ISSUE TITLE
Normalizing the embeddings

### ISSUE THREAD

**Issue by ymitiku** [PaulAlbert31/iMix#1]
In this line, https://github.com/PaulAlbert31/iMix/blob/0f09050da89e337894fef77641ad7d0c6c75465b/main.py#L70, the embeddings `z_i` and `z_j` may have to be normalized.

**Comment by PaulAlbert31** [comment]
Hi,
The L2 normalization of the features is done in the network forward pass [here](https://github.com/PaulAlbert31/iMix/blob/0f09050da89e337894fef77641ad7d0c6c75465b/nets/resnet.py#L105)
Does this address your concern ?
