### ISSUE TITLE
How to train N-pair without i-mix?

### ISSUE THREAD

**Issue by kevinbro96** [PaulAlbert31/iMix#3]
Hi, I want to train a baseline, so
How to train N-pair without i-mix using this repo?
Thanks!

**Comment by PaulAlbert31** [comment]
Hi, thank you for your interest in this implementation.
I added a command line argument to train N-pairs without mixup: --no-mix (added in the README as well)
This should address your issue.
Paul

**Comment by kai-wen-yang** [comment]
Thanks a lot!
