### ISSUE TITLE
iMix+Npair performs worse than Npair

### ISSUE THREAD

**Issue by kai-wen-yang** [PaulAlbert31/iMix#4]
Hi, I use your code to run iMix+Npair vs iMix on CIFAR100 with ResNet18 for 200 epochs. But I find iMix+Npair performs worse than Npair.

**Comment by PaulAlbert31** [comment]
Hello, thank you for your interest in this implementation.
I did not experiment much with running n-pairs by itself. Running the algorithm for 2000 epochs with a ResNet18, I obtain 63.01 of knn classification accuracy with N-pairs alone against 65.28 with iMix+N-pairs. So this might just be a matter of convergence time. 
Did you observe different results with the official implementation ?
